### ISSUE TITLE
Unable to load certificate

### ISSUE THREAD

**Issue by Azaretdodo** [iadgov/Spectre-and-Meltdown-Guidance#23]
hello,

after have launch your fourth line of command i happen one problem so i paste below the fourth line of command finally thank you in advance to help myself follow fully your github,

```
[liveuser@localhost-live ~]$ sudo openssl req -new -x509 -newkey rsa:2048 -subj "/CN=Custom KEK/" -keyout KEK.key -out KEK.crt -days 3650 -nodes -sha256
.......+..+......+.............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+......+........+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*........+.....+....+......+........+...+...+....+...+.....+...+....+..+.+............+...+.........+...+..+......+............+.+.....+.+...+.....+.+......+.....+...+.+..+....+...+........+....+.........+.....+......+.+.........+...+...............+.....+.............+..+.+.....+......+......+..........+...............+...+...........+...+..................+.......+...+..+.+..+...................+.....+.+..+...+....+.....+.+..+......+....+...+.....+...............+....+...+......+.....+.+...+..................+........+......+.+...+...........+.+..+.......+..................+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.+.....+.......+..+.........+.......+...+......+.........+......+...+...+..+......+....+..+.........+............+....+...........+...+.+...+......+.........+......+..+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+.....+...+...+...+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*........+............+.....+....+...............+........+.+.....................+........+...+....+.....+......+.......+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
[liveuser@localhost-live ~]$ sudo openssl req -new -x509 -newkey rsa:2048 -subj "/CN=Custom DBK/" -keyout DBK.key -out KEK.crt -days 3650 -nodes -sha256
...+.+...+..+.+.....+.........+.........+....+..+.+............+.....+.......+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+......+....+.................+....+.....+......+....+...........+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.......+.+...+..+..........+.........+...+......+......+........+.+..+..................+......+....+..+...+.......+.....+....+......+....................+.........+....+.....+....+.................+...+.............+..+.+......+...........+....+.....+....+...........+....+......+.........+..+...+....+...+...+.....+....+..+...+.............+..+..........+.....+...+...+.......+...+..+...+....+......+.........+..+...+..........+...+.........+.........+...........+......+...+....+............+...+..+......+...+......+.+..+.......+...+......+.....+....+............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
..+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+..+...+....+.....+.............+........+.......+..+.........+....+...+...+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*........+...............+....+...+........+....+...+............+..+..........+........+.+......+........+.+...........+....+..+....+......+.....+....+.....................+...+......+...+..+......+...+..........+......+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
[liveuser@localhost-live ~]$ sudo openssl x509 -outform der -in KEK.crt -out KEK.cer
[liveuser@localhost-live ~]$ sudo openssl x509 -outform der -in DBK.crt -out DBK.cer
Could not open file or uri for loading certificate from DBK.crt
001E0323B37F0000:error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:crypto/store/store_register.c:237:scheme=file
001E0323B37F0000:error:80000002:system library:file_open:No such file or directory:providers/implementations/storemgmt/file_store.c:267:calling stat(DBK.crt)
Unable to load certificate
```

regards.

Azaretdodo.

**Comment by Harvester57** [comment]
You need to change the -out parameter on the second command, from `-out KEK.crt` to `-out DBK.crt`

**Comment by Harvester57** [comment]
Please note that the correct is provided here: https://github.com/nsacyber/Hardware-and-Firmware-Security-Guidance/blob/master/secureboot/Linux.md#21-create-certificates-and-keys

**Comment by Azaretdodo** [comment]
I have type the good so you are in a dreams,

Azaretdodo.
________________________________

**Comment by Harvester57** [comment]
Check again the second command that you used, and please be more respectful with people trying to help you :)

**Comment by Azaretdodo** [comment]
I have the true you dream so i paste below the copy from the line of command finally you should be useful or you leave this list

***@***.*** ~]$ sudo openssl req -new -x509 -newkey rsa:2048 -subj "/CN=Custom KEK/" -keyout KEK.key -out KEK.crt -days 3650 -nodes -sha256
.......+..+......+.............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+......+........+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*........+.....+....+......+........+...+...+....+...+.....+...+....+..+.+............+...+.........+...+..+......+............+.+.....+.+...+.....+.+......+.....+...+.+..+....+...+........+....+.........+.....+......+.+.........+...+...............+.....+.............+..+.+.....+......+......+..........+...............+...+...........+...+..................+.......+...+..+.+..+...................+.....+.+..+...+....+.....+.+..+......+....+...+.....+...............+....+...+......+.....+.+...+..................+........+......+.+...+...........+.+..+.......+..................+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.+.....+.......+..+.........+.......+...+......+.........+......+...+...+..+......+....+..+.........+............+....+...........+...+.+...+......+.........+......+..+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+.....+...+...+...+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*........+............+.....+....+...............+........+.+.....................+........+...+....+.....+......+.......+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
***@***.*** ~]$ sudo openssl req -new -x509 -newkey rsa:2048 -subj "/CN=Custom DBK/" -keyout DBK.key -out KEK.crt -days 3650 -nodes -sha256
...+.+...+..+.+.....+.........+.........+....+..+.+............+.....+.......+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+......+....+.................+....+.....+......+....+...........+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.......+.+...+..+..........+.........+...+......+......+........+.+..+..................+......+....+..+...+.......+.....+....+......+....................+.........+....+.....+....+.................+...+.............+..+.+......+...........+....+.....+....+...........+....+......+.........+..+...+....+...+...+.....+....+..+...+.............+..+..........+.....+...+...+.......+...+..+...+....+......+.........+..+...+..........+...+.........+.........+...........+......+...+....+............+...+..+......+...+......+.+..+.......+...+......+.....+....+............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
..+.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.+..+...+....+.....+.............+........+.......+..+.........+....+...+...+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*........+...............+....+...+........+....+...+............+..+..........+........+.+......+........+.+...........+....+..+....+......+.....+....+.....................+...+......+...+..+......+...+..........+......+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
***@***.*** ~]$ sudo openssl x509 -outform der -in KEK.crt -out KEK.cer
***@***.*** ~]$ sudo openssl x509 -outform der -in DBK.crt -out DBK.cer
Could not open file or uri for loading certificate from DBK.crt
001E0323B37F0000:error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:crypto/store/store_register.c:237:scheme=file
001E0323B37F0000:error:80000002:system library:file_open:No such file or directory:providers/implementations/storemgmt/file_store.c:267:calling stat(DBK.crt)
Unable to load certificate.


Azaretdodo.
________________________________

**Comment by Azaretdodo** [comment]
Big sorry i misunderstood between the line of command two from the line of command four,

You are useful finally that is myself thé dreamer,

Have a nice evening,

Regards.


Azaretdodo.
________________________________
